### ISSUE TITLE
Correções para fazer todos testes passarem

### ISSUE THREAD

**Issue by acenelio** [famarcelino/movieflix#1]
Olá Francisco. Seu trabalho já foi aceito (não precisa ser reenviado). Parabéns!

Caso queira que todos testes passem, favor fazer as seguintes alterações:

1) Em MovieResource, troque o valor padrão do tamanho da paginação para 10:
```
@RequestParam(value = "size", defaultValue = "10") Integer size)
```

2) Em ReviewDTO, acrescente um atributo user do tipo UserDTO:
```
pivate UserDTO user;
```

Não se esqueça de fazer os get/set, e de instanciar esse objeto no construtor:
```
public ReviewDTO(Review entity) {
	(...)
	user = new UserDTO(entity.getUser());
}
```

**Comment by famarcelino** [comment]
Oi Nélio, obrigado!

Fiz as correções e realmente agora todos os casos de testes passaram com sucesso!!!

Grato pelas dicas.

**Comment by famarcelino** [comment]
Erros apontados foram corrigidos.
